#include <stdio.h>

int main() {
    int n0,i,ni=0,a;
    while (scanf("%d",&n0)!=EOF){
        i=1;
        ni=n0;
        printf("Hailstone generated by %d:\n%d ",ni,ni);
        while(1){
            if(ni%2)    ni=ni*3+1;
            else   ni=ni/2;
            if (ni==1){
                i++;
                printf("1\nNumber of hailstone generated:%d\n\n",i);
                break;
            }
            printf("%d ",ni);
            i++;
        }
    }
    return 0;
}